import os
import requests
import json
import subprocess


def get_pr_diff(repo, pr_number, token):
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3.diff",
    }
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.text


from openai import OpenAI


def analyze_diff_with_ai(diff_content, api_key):
    print("Sending diff to AI for analysis...")

    if api_key == "mock_key":
        if len(diff_content) < 50:
            return "Minor changes detected. No architectural updates required."
        summary = "### AI Review Summary\n\n"
        summary += "- **Architectural Impact**: Possible updates to dependencies or core logic.\n"
        summary += "- **Documentation**: Consider updating developer guides for these changes.\n"
        summary += "- **Suggestions**: Ensure test coverage is maintained for the modified lines.\n"
        return summary

    try:
        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": "You are a senior software architect. Analyze this diff and provide a PR review focusing on architectural impact, documentation needs, and suggestions.",
                },
                {"role": "user", "content": f"Here is the diff:\n\n{diff_content}"},
            ],
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error querying OpenAI: {e}")
        return "AI analysis failed due to an error."


def post_pr_comment(repo, pr_number, token, comment):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    data = {"body": comment}
    response = requests.post(url, headers=headers, json=data)
    response.raise_for_status()
    print("Successfully posted AI review comment to PR.")


def generate_dev_docs(api_key):
    print("Generating developer documentation updates...")
    os.makedirs("docs/developer", exist_ok=True)

    if api_key == "mock_key":
        doc_content = "# Developer Onboarding\n\nGenerated by AI Agent based on repository state.\n\n## Architecture Summary\nThis repository handles automated CI/CD and self-documentation."
    else:
        try:
            with open("repo_state.json", "r") as f:
                state = json.load(f)
            client = OpenAI(api_key=api_key)
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {
                        "role": "system",
                        "content": "You are an AI technical writer. Create a developer onboarding document based on this repository state JSON. Include sections for overview, tech stack, and structure.",
                    },
                    {"role": "user", "content": json.dumps(state)},
                ],
            )
            doc_content = response.choices[0].message.content
        except Exception as e:
            print(f"Failed to generate dynamic docs: {e}")
            doc_content = "# Developer Onboarding\n\nAI generation failed."

    with open("docs/developer/onboarding.md", "w") as f:
        f.write(doc_content)
    print("Generated docs/developer/onboarding.md")


def main():
    print("Starting AI Documentation Agent...")

    # Environment variables injected by GitHub Actions
    token = os.environ.get("GITHUB_TOKEN")
    api_key = os.environ.get("OPENAI_API_KEY", "mock_key")
    repo = os.environ.get("GITHUB_REPOSITORY", "user/repo")
    pr_number = os.environ.get("PR_NUMBER")
    event_name = os.environ.get("EVENT_NAME")

    if event_name == "pull_request" and pr_number and token:
        try:
            diff = get_pr_diff(repo, pr_number, token)
            ai_summary = analyze_diff_with_ai(diff, api_key)
            post_pr_comment(repo, pr_number, token, ai_summary)

            # Generate or update docs based on the PR
            generate_dev_docs(api_key)
        except Exception as e:
            print(f"Error processing PR: {e}")
    else:
        print(
            "Not a PR event or missing credentials. Running standalone doc generation."
        )
        generate_dev_docs(api_key)


if __name__ == "__main__":
    main()
